BEGIN;

INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('58636fa1-edea-483d-b7bb-d5e330e40df9', 'Vitor Conselheiro', '34991689724', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('3f55a2e6-2ec0-45ba-88e2-4480c2f74efc', 'Luiz Mario', '34988049231', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('963a57f5-816d-494f-9a50-8a1be4c1ff07', 'Ana Carolina Machado', '34988346418', NULL, 'Rua Professor Walter Fernandes', '511', NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('3d0e28f4-c36a-4120-9c13-dab257f655dc', 'Keile Guinder', '34997670863', NULL, 'Rua Antonio Rezende Filho', '90', NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', '1983-06-09') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('07585aeb-da01-41a5-ae83-2719c159d29b', 'Lucivaldo', '34988799615', NULL, 'Rua Antonio Rezende Filho', 'Fatima', NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('d1d4d057-36e9-4a9c-8fb8-519e4de0f133', 'Sueli Lemes Cortes', '34988782899', NULL, 'Rua Maike Henrique Fazolim', '45', NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('99dadcb5-7460-4729-b80a-0435b28e86b0', 'Michele Vitoriano', '34996590769', NULL, 'Zona Rural', NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', '1990-05-22') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('0c69cdca-7bec-433c-a8ca-dd9099e4d354', 'Cristian Victor Faleiros', '34992039286', NULL, 'Av Rui Dacio de Belem Miguel', NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', '1999-07-05') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('6d9685d4-cbbd-42d8-a2c4-e923cfb75264', 'Renata Regina da Silva', '34988188523', NULL, 'Av. Batalhao Maua', '900', NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('1b32272a-dd87-4fd7-af52-ff861df2010b', 'Sulamita da Silva Resende Pereira', '34998596325', NULL, 'Rua Ozires Paranhos', '211', NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', '1967-02-28') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('e0202c56-bb9f-44bc-8e96-3eda7b829dff', 'Franciele Lemes de Almeida', '34998055442', NULL, 'Ouro Verde', NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', '1987-06-17') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('e1540c2f-d28a-40c6-8d42-b578137234e7', 'Nelci de Fatima Lemos Curcino de Sousa', '34988562829', NULL, 'Rua Antonio Costa de Almeida', '381', NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', '1964-11-27') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('ed43c97c-201e-4e22-bcb8-b90abcddb4b3', 'Nilsangela Aparecida Sousa Rafael', '34988046325', NULL, 'Rua Antonio Costa de Almeida', '381', NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', '1982-06-03') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('b0467da9-4c88-40cd-8188-4c3027f887f1', 'Geordania Cristina', '34992511204', NULL, 'Rua Maurilio Pirette', '450', NULL, 'Araguari - MG', 'Pessoa', false, 'GABINETE', NULL) ON CONFLICT (id) DO NOTHING;

COMMIT;
