BEGIN;

INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('77e33cab-b873-4073-9561-8111607fd8d4', 'Elisângela Mendonça Rocha', '34984412729', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'BEZERRA MENEZES NATAL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('66b7eaca-af06-472c-833c-b7d0af94ab2c', 'Renata de Oliveira Silva', '34997257962', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'BEZERRA MENEZES NATAL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('4e999885-8617-410c-8f31-be857b483ce4', 'Joelma Pereira da Silva', '34984213033', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'BEZERRA MENEZES NATAL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('2f3c76ce-0d4d-40a5-806c-d21213f28850', 'Ivonete Pereira de Moura', '34999518358', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'BEZERRA MENEZES NATAL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('6b0f34e9-000b-4348-813a-904ecf7c29bb', 'Ketlen Cristina', '34997406226', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'BEZERRA MENEZES NATAL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('4ad72bb2-0739-4866-b187-e2f2001b86b0', 'Márcia Cristina B. Silva Oliveira', '34988970308', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'BEZERRA MENEZES NATAL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('2347d110-5330-4b32-a4ea-0e42ab2274e4', 'Patrícia Maria Moreira Gomes', '34988219902', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'BEZERRA MENEZES NATAL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('81d2cdaa-929f-46c8-8f83-153727bb39bb', 'Juliana Fernandes', '34997660443', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'BEZERRA MENEZES NATAL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pessoa (id, full_name, phone, phone_extra, address, address_number, neighborhood, city, person_type, atendimento_humano, destino, birth_date) VALUES ('baa27d51-a899-4c49-9e64-33a8fcd22b87', 'Lorrayne Joana Francisca da Silva Lopes', '34991956335', NULL, NULL, NULL, NULL, 'Araguari - MG', 'Pessoa', false, 'BEZERRA MENEZES NATAL', NULL) ON CONFLICT (id) DO NOTHING;

COMMIT;
